<?php
require_once './../util/initialize.php';
include 'common/upper_content.php';
?>
<style>
td{
	font-size:9px;
}
</style>

<!--page content--> 

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">           

            <div class="title_right">
                <button type="button" id="btn_print" class="btn btn-default" style="float: right;"><i class="glyphicon glyphicon-print"></i>  Print</button>
            </div>
			
        </div>

        

        <div class="row">
            <div class="row" id="divInvoice">
                
                <div class="col-md-12 col-sm-12 col-xs-12 table-responsive" id="print_div">
                    <div class="x_panel">
                        <div class="x_title" style="background-color: #424242;color:white;border-radius: 5px 5px 0px 0px;"><h3><center>Stock Sheet</center></h3></div>
                        <div class="x_content">
                            <div class="table-responsive">
                               
                                <table id="sata_table" class="table-bordered " cellspacing="0" width="100%">
                                    <thead>
                                        <td>Item Name</td>
										<td style='width:90px;'></td>
										<td style='width:90px;'></></td>
										<td style='width:90px;'></></td>
										<td style='width:90px;'></></td>
                                        
                                    </thead>
                                    <tbody id="table_body">
                                        <?php 
                                        foreach (Category::find_all() as $category) {
                                            $inventory_details = Inventory::find_all_by_category_id($category->id);
                                            $category_name     = $category->name;
                                            $sub_total = 0;?>
                                        <tr style="background-color: gray;color:black;"><td colspan="10" ><b><?=$category_name?></b></td></tr>
                                        <tr>
                                            
											<th></th>
                                            
                                            
                                        </tr>
                                            <?php foreach ($inventory_details as $inventory_detail) {
                                                $batch_details   = Batch::find_by_id($inventory_detail['batch_id']);
                                                $product_details = Product::find_by_id($inventory_detail['product_id']);
                                                $product_name    = Product::find_by_id($inventory_detail['product_id'])->name;
                                                $line_total      = ($inventory_detail['qty']) * ($batch_details->wholesale_price);
                                                $sub_total      +=$line_total;  
                                                
                                         ?>
                                        
                                        <tr>
                                            <td><?=$product_name?></td>                                            
                                            <td></td>
											<td></td>
											<td></td>
											<td></td>
                                            
                                        </tr>
                                        
                                       <?php
                                       
                                            }
                                            ?>
                                        
                                            <?php
                                       }
                                       ?>
                                    </tbody>
                                    <tfoot style="margin-top: 10px;">
<!--                                        <tr><td colspan="9">&nbsp;</td></tr>-->
                                        
                                        <tr style="background-color: #424242;color: white;">
                                            <td colspan="10" style="text-align: center;">Report Generated by <?=$_SESSION['user']['name']." on ".date("Y/m/d")." at ".date("h:i:sa");?></td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

<?php include 'common/bottom_content.php'; ?>

<script>
 
    //print_div
    
     $('#btn_print').click(function (){
              PrintDiv();
        });
     
        function PrintDiv() {    
            var divToPrint = document.getElementById('print_div');
            var popupWin = window.open('', '_blank', 'width=800,height=500');
            popupWin.document.open();
            popupWin.document.write('<html><head><link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"></head><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
            popupWin.document.close();
        }
</script>








